---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - HTML_HTMLHINT
  - JSON_PRETTIER
  - KUBERNETES_HELM
  - KUBERNETES_KUBECONFORM
  - KUBERNETES_KUBESCAPE
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_PYLINT
  - REPOSITORY_GITLEAKS
  - YAML_PRETTIER
  - YAML_YAMLLINT

YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "helm/.*"
DISABLE_ERRORS: false
SPELL_CSPELL_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PARALLEL: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: false
LOG_LEVEL: INFO
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "-q"

PRE_COMMANDS:
  - command: pip install -r /github/workspace/requirements.txt
    venv: pylint

PLUGINS:
  - https://raw.githubusercontent.com/shiranr/linkcheck/v2.0.17.beta/mega-linter-plugin-linkcheck/linkcheck.megalinter-descriptor.yml
