app:
  ingress:
    host: "dns-form-dev.cloud-platform.service.justice.gov.uk"

  deployment:
    replicaCount: 1
    env:
      SENTRY_ENV: "development"
      FLASK_DEBUG: true
      PHASE_BANNER_TEXT: "DEV"
