app:
  ingress:
    host: "change-dns.service.justice.gov.uk"

  deployment:
    replicaCount: 3
    env:
      SENTRY_ENV: "production"
      FLASK_DEBUG: false
      PHASE_BANNER_TEXT: "PRIVATE BETA"
